site_name: Board Game Teaches

nav:
  - Home: index.md
  - Big_Games:
    - Black Forest: black_forest.md
    - Calimala: calimala.md
    - Cuzco: cuzco.md
    - Gaia Project: gaia_project.md
    - Great Western Trail: great_western_trail.md
    - Inferno: inferno.md
    - Revive: revive.md
    - Shipyard: shipyard.md
    - Trickerion: trickerion.md
    - Unconcious Mind: unconcious_mind_template.md
  - Card_Games:
    - Bid Coin: bid_coin.md
    - Savage Bowl: savage_bowl.md

theme:
  name: material

markdown_extensions:
  - attr_list  # Allows adding HTML-style attributes like {.class}
  - md_in_html # Allows Markdown inside raw HTML blocks (like <div>)
  - admonition
 # - codehilite
 # - toc:
 #   permalink: true
 # - pymdownx.superfences
 # - pymdownx.tabbed
